Traceback (most recent call last):
  File "/Users/gy22808/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/gy22808/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/gy22808/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/gy22808/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/gy22808/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/gy22808/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/gy22808/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/gy22808/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
data = {
    'apples': [3, 2, 0, 1], 
    'oranges': [0, 3, 7, 2]
}
purchases = pd.DataFrame(data)
purchases
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      2[0m data [38;5;241m=[39m {
[1;32m      3[0m     [38;5;124m'[39m[38;5;124mapples[39m[38;5;124m'[39m: [[38;5;241m3[39m, [38;5;241m2[39m, [38;5;241m0[39m, [38;5;241m1[39m], 
[1;32m      4[0m     [38;5;124m'[39m[38;5;124moranges[39m[38;5;124m'[39m: [[38;5;241m0[39m, [38;5;241m3[39m, [38;5;241m7[39m, [38;5;241m2[39m]
[1;32m      5[0m }
[1;32m      6[0m purchases [38;5;241m=[39m pd[38;5;241m.[39mDataFrame(data)

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py:22[0m, in [0;36m<module>[0;34m[0m
[1;32m     19[0m [38;5;28;01mdel[39;00m hard_dependencies, dependency, missing_dependencies
[1;32m     21[0m [38;5;66;03m# numpy compat[39;00m
[0;32m---> 22[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompat[39;00m [38;5;28;01mimport[39;00m is_numpy_dev [38;5;28;01mas[39;00m _is_numpy_dev
[1;32m     24[0m [38;5;28;01mtry[39;00m:
[1;32m     25[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_libs[39;00m [38;5;28;01mimport[39;00m hashtable [38;5;28;01mas[39;00m _hashtable, lib [38;5;28;01mas[39;00m _lib, tslib [38;5;28;01mas[39;00m _tslib

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/__init__.py:14[0m, in [0;36m<module>[0;34m[0m
[1;32m     11[0m [38;5;28;01mimport[39;00m [38;5;21;01mplatform[39;00m
[1;32m     12[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m
[0;32m---> 14[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_typing[39;00m [38;5;28;01mimport[39;00m F
[1;32m     15[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompat[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnumpy[39;00m [38;5;28;01mimport[39;00m (
[1;32m     16[0m     is_numpy_dev,
[1;32m     17[0m     np_version_under1p19,
[1;32m     18[0m     np_version_under1p20,
[1;32m     19[0m )
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompat[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyarrow[39;00m [38;5;28;01mimport[39;00m (
[1;32m     21[0m     pa_version_under1p01,
[1;32m     22[0m     pa_version_under2p0,
[1;32m     23[0m     pa_version_under3p0,
[1;32m     24[0m     pa_version_under4p0,
[1;32m     25[0m )

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/pandas/_typing.py:78[0m, in [0;36m<module>[0;34m[0m
[1;32m     73[0m     npt: Any [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m     76[0m [38;5;66;03m# array-like[39;00m
[0;32m---> 78[0m ArrayLike [38;5;241m=[39m Union[[38;5;124m"[39m[38;5;124mExtensionArray[39m[38;5;124m"[39m, [43mnp[49m[38;5;241;43m.[39;49m[43mndarray[49m]
[1;32m     79[0m AnyArrayLike [38;5;241m=[39m Union[ArrayLike, [38;5;124m"[39m[38;5;124mIndex[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mSeries[39m[38;5;124m"[39m]
[1;32m     81[0m [38;5;66;03m# scalars[39;00m

[0;31mAttributeError[0m: module 'numpy' has no attribute 'ndarray'
AttributeError: module 'numpy' has no attribute 'ndarray'

